version: "3.7"

services:
  # api service
  s_nest_api:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: 
      - .env
    expose:
      - 5000
    ports:
      - "5000:5000"
    networks:
      - nest_api_network

# shared network
networks:
  nest_api_network:
    driver: bridge

